import React, { useState, useEffect } from 'react';

const DMCA = () => {
    return (
        <div className='footer-content'>
            <h1>DMCA policy</h1>
            <p>This Digital Millennium Copyright Act policy (&#8220;Policy&#8221;) applies to the <a href="https://openlang.one">openlang.one</a> website (&#8220;Website&#8221; or &#8220;Service&#8221;) and any of its related products and services (collectively, &#8220;Services&#8221;) and outlines how this Website operator (&#8220;Operator&#8221;, &#8220;we&#8221;, &#8220;us&#8221; or &#8220;our&#8221;) addresses copyright infringement notifications and how you (&#8220;you&#8221; or &#8220;your&#8221;) may submit a copyright infringement complaint.</p>
            <p>Protection of intellectual property is of utmost importance to us and we ask our users and their authorized agents to do the same. It is our policy to expeditiously respond to clear notifications of alleged copyright infringement that comply with the United States Digital Millennium Copyright Act (&#8220;DMCA&#8221;) of 1998, the text of which can be found at the U.S. Copyright Office <a href="https://www.copyright.gov" target="_blank" rel="nofollow noreferrer noopener external">website</a>. This DMCA policy was created with the help of <a href="https://www.websitepolicies.com/dmca-policy-generator" target="_blank">WebsitePolicies</a>.</p>
            <div class="wpembed-toc"><h3>Table of contents</h3><ol class="wpembed-toc"><li><a href="#what-to-consider-before-submitting-a-copyright-complaint">What to consider before submitting a copyright complaint</a></li><li><a href="#notifications-of-infringement">Notifications of infringement</a></li><li><a href="#changes-and-amendments">Changes and amendments</a></li><li><a href="#reporting-copyright-infringement">Reporting copyright infringement</a></li></ol></div><h2 id="what-to-consider-before-submitting-a-copyright-complaint">What to consider before submitting a copyright complaint</h2>
            <p>Before submitting a copyright complaint to us, consider whether the use could be considered fair use. Fair use states that brief excerpts of copyrighted material may, under certain circumstances, be quoted verbatim for purposes such as criticism, news reporting, teaching, and research, without the need for permission from or payment to the copyright holder.</p>
            <p>Please note that if you are unsure whether the material you are reporting is in fact infringing, you may wish to contact an attorney before filing a notification with us.</p>
            <p>The DMCA requires you to provide your personal information in the copyright infringement notification. If you are concerned about the privacy of your personal information, you may wish to <a href="https://www.copyrighted.com/professional-takedowns" target="_blank">hire an agent</a> to report infringing material for you.</p>
            <h2 id="notifications-of-infringement">Notifications of infringement</h2>
            <p>If you are a copyright owner or an agent thereof, and you believe that any material available on our Services infringes your copyrights, then you may submit a written copyright infringement notification (&#8220;Notification&#8221;) using the contact details below pursuant to the DMCA. All such Notifications must comply with the DMCA requirements. You may refer to a <a href="https://www.copyrighted.com/dmca-notice-generator" target="_blank">DMCA takedown notice generator</a> or other similar services to avoid making mistake and ensure compliance of your Notification.</p>
            <p>Filing a DMCA complaint is the start of a pre-defined legal process. Your complaint will be reviewed for accuracy, validity, and completeness. If your complaint has satisfied these requirements, our response may include the removal or restriction of access to allegedly infringing material. We may also require a court order from a court of competent jurisdiction, as determined by us in our sole discretion, before we take any action.</p>
            <p>If we remove or restrict access to materials or terminate an account in response to a Notification of alleged infringement, we will make a good faith effort to contact the affected user with information concerning the removal or restriction of access.</p>
            <p>Notwithstanding anything to the contrary contained in any portion of this Policy, the Operator reserves the right to take no action upon receipt of a DMCA copyright infringement notification if it fails to comply with all the requirements of the DMCA for such notifications.</p>
            <p>The process described in this Policy does not limit our ability to pursue any other remedies we may have to address suspected infringement.</p>
            <h2 id="changes-and-amendments">Changes and amendments</h2>
            <p>We reserve the right to modify this Policy or its terms related to the Website and Services at any time at our discretion. When we do, we will revise the updated date at the bottom of this page. We may also provide notice to you in other ways at our discretion, such as through the contact information you have provided.</p>
            <p>An updated version of this Policy will be effective immediately upon the posting of the revised Policy unless otherwise specified. Your continued use of the Website and Services after the effective date of the revised Policy (or such other act specified at that time) will constitute your consent to those changes.</p>
            <h2 id="reporting-copyright-infringement">Reporting copyright infringement</h2>
            <p>If you would like to notify us of the infringing material or activity, we encourage you to contact us using the details below:</p>
            <p><a href="&#109;&#097;&#105;&#108;&#116;&#111;&#058;d&#109;i&#116;r&#121;&#64;op&#101;&#110;l&#97;&#110;g&#46;&#111;&#110;e">&#100;mi&#116;&#114;&#121;&#64;&#111;p&#101;&#110;l&#97;ng.&#111;&#110;e</a></p>
            <p>This document was last updated on July 6, 2023</p>
            <p class="madewith"><a href="https://www.websitepolicies.com/dmca-policy-generator?via=madewithbadge" target="_blank"><img width="200" height="25" alt="Made with WebsitePolicies DMCA policy generator" src="https://cdn.websitepolicies.io/img/badge.png" srcSet="https://cdn.websitepolicies.io/img/badge_2x.png 2x"></img></a></p>
        </div>
    )
}

export default DMCA